Blog app - Views
svitalis123/blogapp pull request #6
Opened 2023-01-31 22:57 UTC by svitalis123

# Blog app - Views
## I accomplished

- [ ] Created new Branch view-feature
- [ ] Created Styling
- [ ] Used methods that I created in the Blog App

2023-01-31 23:21 UTC, rloterh reviewed
Hi slu, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented, and adhere(s) to the following standard(s):
- [ ] Kindly ensure that provided guide instructions are removed and/or replaced with appropriate contents applicable under each section of your ReadMe. Similarly, kindly also remove guide notes for _license_ creation under the _license_ section.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-01 07:33 UTC, FrederickMih requested changes
## Hi 🙋  @svitalis123 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)




## Highlights <img src = "https://media.giphy.com/media/dUJXSHVAbkguI/giphy.gif" width = "30"  height = "30"></img>

- Great styling of app(wireframe) ✔️ 
- PR is professional ✔️ 
- All Linter checks passed ✔️ 



## Required Changes ♻️
N/A
_Check the comments under the review._

## Optional suggestions
N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 07:33 UTC, FrederickMih commented on README.md
>  This project is [MIT](./MIT.md) licensed.
- [ ] @svitalis123 license file is currently empty. You'll kindly need to fix 🔧 this.

2023-02-01 07:33 UTC, FrederickMih commented on app/views/users/index.html.erb
> +</div>
- [**Optional**] @svitalis123 as a best practice, instead of using **@object.each**, I'll kindly suggest to use Rails partials. They keep your codebase DRY. For hints only, check out the piece of code below:

```ruby
# app/views/users/_user.html.erb

     #   HTML Code Here displaying
     #   user.photo, user.name and user.posts_counter

    # app/views/users/index.html.erb

    <%= render @users %>
```

2023-02-01 07:33 UTC, FrederickMih commented on app/views/users/show.html.erb
> +    </div>
- [Optional] This piece of code is being used repeatedly. Check out the comments above to adhere to best practices.

2023-02-01 07:33 UTC, FrederickMih commented on app/views/users/index.html.erb
> +        <h3><%= user.Name %></h3>
- [ ] As requested in the project's requirements, kindly make sure that clicking on each user, routes to the user's show page(/users/:id). Hence we'll require a link. Hints

```
<a href ="/users/<%= user.id %>">
        <h3><%= user.Name %></h3>
 </a>
```


**link_to** helper can work best.

2023-02-01 07:33 UTC, FrederickMih commented on app/views/users/show.html.erb
> +  <% @posts.each do |post|%>
- [ ] We really need to render only the 3 most recent posts on each user show page, not all the posts. You had a method that does that in your user model **_Hints_**:

` <% @user.recent_three_posts.each do |post|%>`

2023-02-01 07:33 UTC, FrederickMih commented on app/views/users/show.html.erb
> +    <button id="show_container_user_button">See all posts</button>
- [ ] Let's kindly make sure that this button is clickable. Clicking on it opens the user's post index page. Hints above ⬆️

2023-02-01 07:33 UTC, FrederickMih commented on app/views/posts/index.html.erb
> +    <% @posts.each do |post|%>
- [ ] Kindly render only 5 recent comments for each post as requested. The method `recent_commemnt` you implemented in the post model will do that perfectly 👍

2023-02-01 12:23 UTC, mwanawabangona approved these changes
Hi @svitalis123 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)
H
## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 12:33 UTC, merged